package com.mo.mediaodyssey.auth.model;

import jakarta.persistence.Id;

import java.util.Collection;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;

@Entity
public class User implements UserDetails {

    // Inspiried by:
    // https://www.baeldung.com/jakarta-persistence-3-2
    // https://github.com/bobbychansfu/cmpt276-2026-1/blob/main/src/main/java/com/example/demo/models/Users.java
    // Documentation was reviewed afterwards:
    // https://jakarta.ee/specifications/persistence/3.0/apidocs/jakarta.persistence/jakarta/persistence/package-summary
    // https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/core/userdetails/UserDetails.html

    /**
     * Id for MO User. Primary key. Automatically assigned.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Email address for MO User. Must be unique.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * Username for MO User. By default, matches email address. Can be changed by MO
     * User. Does not need to be unique.
     * TODO: logic to self-serve update a User details to be implemented in the
     * future.
     */
    @Column(nullable = false)
    private String username;

    /**
     * Password for MO User.
     */
    @Column(nullable = false)
    private String password;

    /**
     * isEnabled MO User. Used to determine if email verification has been complete.
     * By default, false, as User needs to verify email.
     * 
     * Logic handled in MOAuthenticationProvider. Adding more in the future requires
     * implementing its logic in MOAuthenticationProvider.
     */
    private boolean isEnabled = false;

    /**
     * isAccountNonLocked MO User. Used to determine if MO User account has been not
     * locked by an Admin. By default, true (Account is not locked).
     * 
     * Logic handled in MOAuthenticationProvider. Adding more in the future requires
     * implementing its logic in MOAuthenticationProvider.
     */
    private boolean isAccountNonLocked = true;

    // TODO: add roles: REGULAR_USER, ADMIN_USER

    // Constructor, Getters, and Setters generated by GitHub Copilot
    public User() {
        // Required by JPA
    }

    public User(String email, String username, String password) {
        this.email = email;
        this.username = username;
        this.password = password;
    }

    public User(String email, String username, String password, boolean isEnabled, boolean isAccountNonLocked) {
        this.email = email;
        this.username = username;
        this.password = password;
        this.isEnabled = isEnabled;
        this.isAccountNonLocked = isAccountNonLocked;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public boolean isEnabled() {
        return isEnabled;
    }

    public void setEnabled(boolean enabled) {
        isEnabled = enabled;
    }

    @Override
    public boolean isAccountNonLocked() {
        return isAccountNonLocked;
    }

    public void setAccountNonLocked(boolean accountNonLocked) {
        isAccountNonLocked = accountNonLocked;
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        // TODO: implement roles
        throw new UnsupportedOperationException("Unimplemented method 'getAuthorities'");
    }
}