spring.application.name=mediaodyssey
server.port=${PORT:8080}
spring.h2.console.enabled=true

spring.config.import=optional:file:.env[.properties]

tmdb.api.key=${TMDB_API_KEY}

spotify.client.id=${SPOTIFY_CLIENT_ID}
spotify.client.secret=${SPOTIFY_CLIENT_SECRET}

rawg.api.key=${RAWG_API_KEY}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# explicitly set dialect for Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update